version: "2"
services:
  api:
    image: api
    container_name: api
    restart: always
    ports:
      - "3333:3000"
    networks:
      - my_network
  ui:
    image: ui
    container_name: ui
    restart: always
    ports:
      - "80:80"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

