export const MINIO_CONFIG = {
    MINIO_ENDPOINT: 'localhost',
    MINIO_PORT: 9000,
    MINIO_ACCESSKEY: 'raFbO5Jd5J4viToMJXOp',
    MINIO_SECRETKEY: 'nzBUkqZeporN4UWRTe9yaN1y7ZG40A6X2IfQLKdG',
    MINIO_BUCKET: 'kgb',
};