export const MINIO_CONFIG = {
    MINIO_ENDPOINT: 'localhost',
    MINIO_PORT: 9000,
    MINIO_ACCESSKEY: 'NQVvaroIkaCFNQx7sW7M',
    MINIO_SECRETKEY: '7Odt6K0Kocpef4ZwMOM0fYRuxr59xx0Si4gKR3bu',
    // MINIO_ACCESSKEY: 'MfRX0XK1cuRy96Qbt1um',
    // MINIO_SECRETKEY: 'uL6vkgTXBFezxIgr3gxXLXWxqETLlYRLvgxsy5T8',
    MINIO_BUCKET: 'kgms',
};