export const MINIO_CONFIG = {
    MINIO_ENDPOINT: 'localhost',
    MINIO_PORT: 9000,
    MINIO_ACCESSKEY: 'NQVvaroIkaCFNQx7sW7M',
    MINIO_SECRETKEY: '7Odt6K0Kocpef4ZwMOM0fYRuxr59xx0Si4gKR3bu',
    // MINIO_ACCESSKEY: 'N6arKRvfRG9hQsxV9cgs',
    // MINIO_SECRETKEY: 'Yq5X3hPr3MuYsELEdlexwHk5ZhO6Er76okVyp3DZ',
    MINIO_BUCKET: 'kgms',
};