version: '3.1'
services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
      - "9999:9999"
    restart: always
    command: server /data --console-address ":9999"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    read_only: true
    volumes:
      - ./data:/data
      - ./config:/root/.minio

