version: "2"
services:
  arango:
    image: arangodb/arangodb:latest
    container_name: arango
    environment:
    - ARANGO_ROOT_PASSWORD=root
    volumes:
    - ./data:/var/lib/arangodb3 
    restart: always
    ports:
    - "8529:8529"
    networks:
      - my_network


networks:
  my_network:
    driver: bridge